### ISSUE TITLE
Error: Cannot find module '/portfolio-website/.next/server/app/page_client-reference-manifest.js'

### ISSUE THREAD

**Issue by aungkoman** [ByteGrad/portfolio-website#12]
When we run 

```bash
next start
```

we have following error logs

```bash

msd@MSDs-Mac-mini portfolio-website % next start   
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 188ms
Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/portfolio-website/.next/server/app/page_client-reference-manifest.js'
Require stack:
- /usr/local/lib/node_modules/next/dist/server/load-components.js
- /usr/local/lib/node_modules/next/dist/server/next-server.js
- /usr/local/lib/node_modules/next/dist/server/next.js
- /usr/local/lib/node_modules/next/dist/server/lib/start-server.js
- /usr/local/lib/node_modules/next/dist/cli/next-start.js
- /usr/local/lib/node_modules/next/dist/lib/commands.js
- /usr/local/lib/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at /usr/local/lib/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at mod.require (/usr/local/lib/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadClientReferenceManifest (/usr/local/lib/node_modules/next/dist/server/load-components.js:43:72)
    at loadComponentsImpl (/usr/local/lib/node_modules/next/dist/server/load-components.js:65:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.findPageComponentsImpl (/usr/local/lib/node_modules/next/dist/server/next-server.js:439:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/next/dist/server/load-components.js',
    '/usr/local/lib/node_modules/next/dist/server/next-server.js',
    '/usr/local/lib/node_modules/next/dist/server/next.js',
    '/usr/local/lib/node_modules/next/dist/server/lib/start-server.js',
    '/usr/local/lib/node_modules/next/dist/cli/next-start.js',
    '/usr/local/lib/node_modules/next/dist/lib/commands.js',
    '/usr/local/lib/node_modules/next/dist/bin/next'
  ]
}


```

**Comment by aungkoman** [comment]
in localhost:3000 we got Internal Server Error
